### ISSUE TITLE
allow to install scriptkeeper without git or cargo

### ISSUE THREAD

**Issue by soenkehahn** [Originate/scriptkeeper#193]
The readme should provide an easy one-liner to install `scriptkeeper`. This could be done with either some bash script and binary releases to github or with [snap](https://snapcraft.io/).

**Comment by astampoulis** [comment]
The Rust part in the `snap` link seems to suggest that it's easy to compile Rust code with `musl`. If that is indeed so, a binary release on github would be simple to set up and would be a binary that could be dropped in easily in most Linux systems.

**Comment by soenkehahn** [comment]
The `libc` crate and the `nix` crate don't expose the same api when compiling for the target `x86_64-unknown-linux-musl`. So we can't easily compile a statically linked binary. Not sure how much work that would be, if possible at all.

But I also don't think it's necessary to use a static binary -- as long as the dynamic dependencies are available and installed by default on the systems we want `scriptkeeper` to be used on. Not sure how to judge that, though...

**Comment by soenkehahn** [comment]
Just tried to run a `scriptkeeper` binary on alpine in docker and it doesn't work due to missing dynamic dependencies. So binaries are probably a bad way to distribute this.

**Comment by astampoulis** [comment]
I do not understand your first point (about the `libc` and `nix` crate), maybe we should discuss this offline?

Also, here's one thing to try out too: [clodl](https://github.com/tweag/clodl). This is for turning a dynamic binary plus all its library dependencies into a standalone package that can work anywhere.

**Comment by soenkehahn** [comment]
We have an official binary release now: https://github.com/Originate/scriptkeeper/releases
